<<<<<<< HEAD
package scanner
<<<<<<< HEAD
=======

>>>>>>> d368b1247ac28049a0fc6d8be74855a50d3f7e85
=======

var HighPatterns = []*Pattern{
	// ========================================================================
	//патеры платёжных систем
	// ========================================================================
	MustNewPattern("paypal-secret-assignment", "PayPal Secret Assignment", LevelHigh,
		[]string{"paypal", "payment", "secret", "env"},
		`(?i)(?:paypal[_-]?(?:client[_-]?)?(?:secret|live[_-]?secret|sandbox[_-]?secret|oauth[_-]?secret))["']?\s*[:=]\s*["']?([A-Za-z0-9_-]{50,})`,
	),
	MustNewPattern("yookassa-api-key", "YooKassa API Key", LevelHigh,
		[]string{"yookassa", "yandex", "payment", "api-key", "russia"},
		`(?i)(?:yookassa|yandex[_-]?kassa)[_-]?(?:api[_-]?)?key["']?\s*[:=]\s*["']?([A-Za-z0-9_-]{30,})["']?`,
	),

	MustNewPattern("robokassa-merchant", "Robokassa Merchant Credentials", LevelHigh,
		[]string{"robokassa", "payment", "merchant", "russia"},
		`(?i)robokassa[_-]?(?:merchant[_-]?)?(?:id|password|secret)["']?\s*[:=]\s*["']?([A-Za-z0-9_-]{10,})["']?`,
	),

	// ========================================================================
	//патеры для баз данных
	// ========================================================================
	MustNewPattern("db-conn-postgres", "PostgreSQL Connection String", LevelHigh,
		[]string{"database", "postgres", "connection-string", "credential"},
		`(?i)postgres(?:ql)?:\/\/[^:\s]+:[^@\s]+@[\w\.-]+(?:\:\d+)?\/[\w\.-]+`,
	),
	MustNewPattern("db-conn-mysql", "MySQL Connection String", LevelHigh,
		[]string{"database", "mysql", "mariadb", "connection-string"},
		`(?i)mysql:\/\/[^:\s]+:[^@\s]+@[\w\.-]+(?:\:\d+)?\/[\w\.-]+`,
	),
	MustNewPattern("db-conn-mongodb", "MongoDB Connection String", LevelHigh,
		[]string{"database", "mongodb", "nosql", "connection-string"},
		`(?i)mongodb(?:\+srv)?:\/\/[^:\s]+:[^@\s]+@[\w\.-]+(?:\:\d+)?\/?[\w\.-]*`,
	),
	MustNewPattern("db-conn-redis", "Redis Connection String", LevelHigh,
		[]string{"database", "redis", "cache", "connection-string"},
		`(?i)redis:\/\/(?::[^@]+@|[^:]+:[^@]+@)[\w\.-]+(?:\:\d+)?`,
	),
	MustNewPattern("db-conn-generic-password", "Generic DB Password in String", LevelHigh,
		[]string{"database", "password", "heuristic", "connection-string"},
		`(?i)(?:connection[_-]?string|connstr|db[_-]?conn).*?(?:password|passwd|pwd|secret)["']?\s*[:=]\s*["']?[^\s;"']{8,}`,
	),
	// ========================================================================
	// патеры облачных инфроструктур
	// ========================================================================
	MustNewPattern("aws-access-key-id", "AWS Access Key ID", LevelHigh,
		[]string{"aws", "cloud", "iam", "access-key"},
		`(?:A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}`,
	),
	MustNewPattern("aws-secret-access-key", "AWS Secret Access Key", LevelHigh,
		[]string{"aws", "cloud", "iam", "secret", "credential"},
		`(?i)(?:aws|amazon)[_-]?(?:secret|key)[_-]?(?:access)?["']?\s*[:=]\s*["']?([0-9a-zA-Z/+]{40})["']?`,
	),
	MustNewPattern("gcp-api-key", "Google Cloud Platform API Key", LevelHigh,
		[]string{"gcp", "google", "cloud", "api-key"},
		`AIza[0-9A-Za-z\-_]{35}`,
	),
	MustNewPattern("gcp-service-account-hint", "GCP Service Account Config Hint", LevelHigh,
		[]string{"gcp", "google", "service-account", "json"},
		`(?i)"type"\s*:\s*"service_account".*?"private_key_id"\s*:\s*"[0-9a-f]{40}"`,
	),
	MustNewPattern("azure-storage-key", "Azure Storage Account Key", LevelHigh,
		[]string{"azure", "cloud", "storage", "account-key"},
		`(?i)(?:accountkey|azure[_-]?storage[_-]?key)["']?\s*[:=]\s*["']?([a-zA-Z0-9+/]{86}==?)["']?`,
	),
	MustNewPattern("azure-conn-string", "Azure Storage Connection String", LevelHigh,
		[]string{"azure", "cloud", "storage", "connection-string"},
		`(?i)DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[^;]+;EndpointSuffix=core\.windows\.net`,
	),
	MustNewPattern("yandex-iam-token", "Yandex Cloud IAM Token", LevelHigh,
		[]string{"yandex", "cloud", "iam", "token", "russia"},
		`\b(?:t1|y0)\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]{20,}\b`,
	),
	// ========================================================================
	// патеры приватных ключей
	// ========================================================================
	MustNewPattern("private-key-header", "Private Key Header (SSH/RSA/EC/OPENSSH)", LevelHigh,
		[]string{"crypto", "ssh", "private-key", "pem", "header"},
		`-----BEGIN\s+(?:RSA\s+|DSA\s+|EC\s+|OPENSSH\s+)?PRIVATE\s+KEY-----`,
	),
	MustNewPattern("pgp-private-key-header", "PGP Private Key Block Header", LevelHigh,
		[]string{"crypto", "pgp", "gpg", "private-key", "header"},
		`-----BEGIN\s+PGP\s+PRIVATE\s+KEY\s+BLOCK-----`,
	),
	MustNewPattern("private-key-file-ref", "Private Key File Reference", LevelHigh,
		[]string{"crypto", "ssh", "file-path", "heuristic"},
		`(?i)(?:private[_-]?key|identity[_-]?file)\s*[:=]\s*["']?[~/.]?[\w/-]*(?:id_(?:rsa|dsa|ecdsa|ed25519)|\.pem|\.key)["']?`,
	),
	// ========================================================================
	// токены системы контроля версий
	// ========================================================================
	MustNewPattern("github-pat-classic", "GitHub Personal Access Token (Classic)", LevelHigh,
		[]string{"github", "vcs", "token", "pat"},
		`ghp_[0-9a-zA-Z]{36}`,
	),
	MustNewPattern("github-pat-fine-grained", "GitHub Fine-Grained PAT", LevelHigh,
		[]string{"github", "vcs", "token", "pat"},
		`github_pat_[0-9a-zA-Z]{22}_[0-9a-zA-Z]{59}`,
	),
	MustNewPattern("github-oauth-token", "GitHub OAuth Access Token", LevelHigh,
		[]string{"github", "vcs", "oauth", "token"},
		`gho_[0-9a-zA-Z]{36}`,
	),
	MustNewPattern("gitlab-pat", "GitLab Personal Access Token", LevelHigh,
		[]string{"gitlab", "vcs", "token", "pat"},
		`glpat-[0-9a-zA-Z\-]{20}`,
	),
	MustNewPattern("npm-token", "NPM Access Token", LevelHigh,
		[]string{"npm", "nodejs", "package", "token"},
		`npm_[0-9a-zA-Z]{36}`,
	),
	MustNewPattern("pypi-token", "PyPI Upload Token", LevelHigh,
		[]string{"pypi", "python", "package", "token"},
		`pypi-[A-Za-z0-9\-_]{80,}`,
	),
	MustNewPattern("yandex-oauth-token", "Yandex OAuth Token", LevelHigh,
		[]string{"yandex", "oauth", "token", "russia"},
		`(?i)yandex[_-]?oauth["']?\s*[:=]\s*["']?([A-Za-z0-9_\-\.]{30,})["']?`,
	),
	// ========================================================================
	// возможная личная информация и учёт данных
	// ========================================================================
	MustNewPattern("email-personal-domains", "Email Address (Personal Domains)", LevelHigh,
		[]string{"pii", "email", "personal", "contact"},
		`\b[A-Za-z0-9._%+-]+@(?:yandex\.com|gmail\.com|rambler\.ru|mail\.ru|mail\.com)\b`,
	),
	MustNewPattern("suspicious-username", "Suspicious Username/Role Keyword", LevelHigh,
		[]string{"credential", "username", "role", "heuristic"},
		`(?i)(?:user|login|username|account)["']?\s*[:=]\s*["']?(?:admin|root|deploy|superuser|administrator|sysadmin)["']?`,
	),
	MustNewPattern("password-keyword-assignment", "Password Keyword Assignment", LevelHigh,
		[]string{"credential", "password", "heuristic"},
		`(?i)(?:password|passwd|pwd|pass)["']?\s*[:=]\s*["'][^"'\s]{8,}["']`,
	),
	// ========================================================================
	//API ключи
	// ========================================================================
	MustNewPattern("generic-api-key-assignment", "Generic API Key Assignment", LevelHigh,
		[]string{"api", "key", "credential", "heuristic"},
		`(?i)(?:api[_-]?key|apikey|access[_-]?key|secret[_-]?key|auth[_-]?token)["']?\s*[:=]\s*["']?([A-Za-z0-9_\-\.]{20,})["']?`,
	),
	MustNewPattern("bearer-token-header", "Bearer Token in HTTP Header", LevelHigh,
		[]string{"api", "auth", "bearer", "http-header"},
		`(?i)authorization:\s*bearer\s+[A-Za-z0-9_\-\.+=/]{20,}`,
	),
	MustNewPattern("stripe-api-key", "Stripe API Key", LevelHigh,
		[]string{"stripe", "payment", "api-key"},
		`(?:sk|rk)_(?:live|test)_[0-9a-zA-Z]{24,}`,
	),
	MustNewPattern("slack-api-token", "Slack API Token", LevelHigh,
		[]string{"slack", "chat", "api-key"},
		`xox[baprs]-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*`,
	),
	MustNewPattern("telegram-bot-token", "Telegram Bot API Token", LevelHigh,
		[]string{"telegram", "bot", "api-key"},
		`\b\d{5,}:[A-Za-z0-9_-]{35,}\b`,
	),
	MustNewPattern("yandex-api-key", "Yandex Cloud API Key", LevelHigh,
		[]string{"yandex", "cloud", "api-key", "russia"},
		`(?i)(?:yandex[_-]?(?:cloud[_-]?)?(?:api[_-]?)?key)["']?\s*[:=]\s*["']?([A-Za-z0-9_-]{30,})["']?`,
	),
	MustNewPattern("vk-access-token", "VK API Access Token", LevelHigh,
		[]string{"vk", "vkontakte", "social", "api-key", "russia"},
		`\bvk[a-z0-9_]{56}\b`,
	),
	MustNewPattern("vk-service-token", "VK Service Token", LevelHigh,
		[]string{"vk", "vkontakte", "service-token", "russia"},
		`(?i)vk[_-]?(?:service[_-]?)?token["']?\s*[:=]\s*["']?([A-Za-z0-9_]{40,})["']?`,
	),
	MustNewPattern("cloudpayments-key", "CloudPayments API Key", LevelHigh,
		[]string{"cloudpayments", "payment", "api-key", "russia"},
		`(?i)cloud[_-]?payments[_-]?(?:api[_-]?)?key["']?\s*[:=]\s*["']?([A-Za-z0-9_-]{20,})["']?`,
	),
	MustNewPattern("selectel-api-token", "Selectel API Token", LevelHigh,
		[]string{"selectel", "cloud", "hosting", "api-key", "russia"},
		`(?i)selectel[_-]?(?:api[_-]?)?token["']?\s*[:=]\s*["']?([A-Za-z0-9_-]{30,})["']?`,
	),
	MustNewPattern("regru-api-credentials", "Reg.ru API Credentials", LevelHigh,
		[]string{"regru", "reg.ru", "hosting", "domain", "api-key", "russia"},
		`(?i)reg[_-]?ru[_-]?(?:api[_-]?)?(?:key|token|username)["']?\s*[:=]\s*["']?([A-Za-z0-9_-]{10,})["']?`,
	),

	MustNewPattern("matrix-access-token", "Matrix Access Token", LevelHigh,
		[]string{"matrix", "element", "chat", "access-token"},
		`(?i)matrix[_-]?(?:access[_-]?)?token["']?\s*[:=]\s*["']?([A-Za-z0-9_\-\.]{40,})["']?`,
	),
	// ========================================================================
	// ТЕЛЕГРАМ (ТОКЕНЫ И API - хэш)
	// ========================================================================
	MustNewPattern("telegram-api-credentials", "Telegram API Credentials", LevelHigh,
		[]string{"telegram", "api", "credentials", "messaging"},
		`(?i)telegram[_-]?(?:api[_-]?)?(?:id|hash)["']?\s*[:=]\s*["']?(\d+|[A-Za-z0-9_-]{32})["']?`,
	),
	MustNewPattern("telegram-bot-token", "Telegram Bot Token", LevelHigh,
		[]string{"telegram", "bot", "token", "messaging"},
		`\b\d{5,10}:[A-Za-z0-9_-]{35,}\b`,
	),
	MustNewPattern("telegram-bot-token-assignment", "Telegram Bot Token Assignment", LevelHigh,
		[]string{"telegram", "bot", "token", "env", "config"},
		`(?i)(?:telegram[_-]?)?(?:bot[_-]?)?token["']?\s*[:=]\s*["']?(\d{5,10}:[A-Za-z0-9_-]{35,})["']?`,
	),
	MustNewPattern("telegram-api-hash", "Telegram API Hash", LevelHigh,
		[]string{"telegram", "api", "hash", "mtproto", "auth"},
		`(?i)(?:telegram[_-]?)?api[_-]?hash["']?\s*[:=]\s*["']?([0-9a-fA-F]{32})["']?`,
	),
	MustNewPattern("telegram-api-id", "Telegram API ID", LevelHigh,
		[]string{"telegram", "api", "id", "app-id", "auth"},
		`(?i)(?:telegram[_-]?)?api[_-]?id["']?\s*[:=]\s*["']?(\d{6,10})["']?`,
	),
	MustNewPattern("telegram-api-credentials", "Telegram API Credentials", LevelHigh,
		[]string{"telegram", "api", "credentials", "messaging"},
		`(?i)telegram[_-]?(?:api[_-]?)?(?:id|hash)["']?\s*[:=]\s*["']?(\d+|[A-Za-z0-9_-]{32})["']?`,
	),
	MustNewPattern("telegram-session-string", "Telegram Session String", LevelHigh,
		[]string{"telegram", "session", "pyrogram", "telethon", "auth"},
		`(?i)(?:pyrogram|telethon|telegram)[_-]?session["']?\s*[:=]\s*["']?([A-Za-z0-9_\-+/]{100,})["']?`,
	),
	MustNewPattern("telegram-webapp-init-data", "Telegram WebApp Init Data", LevelHigh,
		[]string{"telegram", "webapp", "mini-app", "init-data", "auth"},
		`(?i)(?:init[_-]?data|telegram[_-]?webapp)["']?\s*[:=]\s*["']?([^"']{100,}hash=[0-9a-fA-F]{64}[^"']*)["']?`,
	),
}
>>>>>>> feature/user-registration
